exclude: (^docs/)|(^.notebooks/)|(^site/)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v3.2.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-ast
      - id: check-toml
      - id: debug-statements
  - repo: https://github.com/floatingpurr/sync_with_poetry
    rev: "0.4.0"
    hooks:
    - id: sync_with_poetry
      args: [--db=sync_with_poetry.json]
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "0.8.0"
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/econchick/interrogate
    rev: "1.5.0"
    hooks:
      - id: interrogate
        args: [-vv, --fail-under=10, src]
  - repo: https://github.com/psf/black
    rev: "22.12.0"
    hooks:
      - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.256"
    hooks:
      - id: ruff
        args: [.]
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.5"
    hooks:
      - id: bandit
        args: [--skip, "B101", --recursive, src]
  - repo: https://github.com/fpgmaas/deptry.git
    rev: "0.8.0"
    hooks:
      - id: deptry
        args: []
  - repo: https://github.com/pycqa/isort
    rev: "5.12.0"
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.990"
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
